# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWKJULktiqDWPFgxxl_r5CCUU6onXewl
"""

pip install pandas scikit-learn matplotlib seaborn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# 1. CRIANDO OS DADOS (Simulação do CSV)
data = {
    'nome': ['Maracanã', 'Arena MRV', 'Vila Belmiro', 'Morumbi', 'Mineirão', 'Independência', 'Castelão', 'Arena da Baixada'],
    'capacidade': [78838, 46000, 16062, 66795, 61846, 23018, 63903, 42372],
    'custo_manutencao': [500, 300, 100, 450, 420, 150, 430, 280] # Valores fictícios
}
df = pd.DataFrame(data)

# Criando a regra (Target): 1 para Elite (> 45k), 0 para Comum
df['elite'] = (df['capacidade'] > 45000).astype(int)

# 2. SEPARANDO X e Y
X = df[['capacidade', 'custo_manutencao']] # O que o modelo estuda
y = df['elite']                           # A resposta que ele quer aprender

# 3. DIVISÃO TREINO E TESTE
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.25, random_state=42)

# 4. PADRONIZAÇÃO (O Scaler que você aprendeu!)
scaler = StandardScaler()
X_treino_scaled = scaler.fit_transform(X_treino)
X_teste_scaled = scaler.transform(X_teste)

# 5. TREINANDO O MODELO
modelo = RandomForestClassifier()
modelo.fit(X_treino_scaled, y_treino)

print("--- Modelo Treinado com Sucesso! ---")

# 6. USANDO O MODELO PARA PREVER UM NOVO ESTÁDIO
# Imagine que um novo estádio foi cadastrado: 50.000 pessoas e custo 350
novo_estadio = [[50000, 350]]
novo_estadio_scaled = scaler.transform(novo_estadio)

predicao = modelo.predict(novo_estadio_scaled)
probabilidade = modelo.predict_proba(novo_estadio_scaled)

print(f"\nResultado da Predição para o novo estádio: {'ELITE' if predicao[0] == 1 else 'COMUM'}")
print(f"Confiança do modelo: {max(probabilidade[0]) * 100}%")